#%RAML 1.0
title: CustomerAPI
version: v1
#baseUri: http://www.example-api.com/{version}
baseUri: https://mocksvc.mulesoft.com/mocks/076a24ff-ca45-497c-beaa-0de18ae36322/{version}
mediaType: application/json


types:
  Address:
    type: object
    properties:
      addressLine1:
        required: false
        type: string
      streetName:
        required: false
        type: string
      suburb:
        required: false
        type: string
      city:
        required: false
        type: string
      country: 
        required: false
        type: string
      
      
  Customer:
    type: object
    properties:
      customerId:
        required: false
      firstName: 
        required: false
        type: string
      lastName: 
        required: false 
        type: string
      address:
        required: false  
        type: Address[]
  Order:
    type: object
    properties:
      orderid: 
        required: true 
        type: number
      customer: 
        required: false
        type: Customer[]
      quantity: 
        required: false
        type: number
      price: 
        required: false
        type: number
      product: Product
      
  
  Product:
    type: object
    properties:
      productName:
        required: true 
        type: string
      category: 
        required: false
        type: string
      
  Result: 
    type: object
    properties:
      message: 
        required: false
        type: string
      code: 
        required: false
        type: number
  
  Error:
    type: object
    properties:
      code:
        required: true
        type: string
      description:
        required: false
        type: string
      
      
      
  

/customers:
  get:
   description: Retrieve list of customers
   responses:
      200:
        body:
          application/json:
            type: Customer[]
            example: |
              
                [
                  {
                    "customerId": "1",
                    "firstName": "Harshitha",
                    "lastName": "Megha",
                    "address": [
                      {
                        "addressLine1": "unit 1",
                        "streetName": "George Street",
                        "suburb": "Sydney CBD",
                        "city": "Sydney",
                        "country": "Australia"
                      
                      }
                    ]
                  }
                
                
                
                
                
                ]
              
              
              
              
      400:
        description: Bad request
        body:
          application/json:
            type: Error
            example: |
              {
                "code": "HTTP 400",
                "description": "Bad request. Check the request"
            
            
              }
          
  post:
    headers:
      UserID:
        description: the identifier for the customer representative who posts a new customer
        type: string
        
    body:
      application/json:
        type: Customer
        example: |
          {
            "firstName": "Harshitha",
            "lastName": "Megha",
              "address": [
                {
                  "addressLine1": "unit 1",
                  "streetName": "George Street",
                  "suburb": "Sydney CBD",
                  "city": "Sydney",
                  "country": "Australia"
                      
                }
              ]
            }
    responses:
      200:
        body:
          application/json:
            type: Result
      
      400:
        body:
          application/json:
            type: Result
            example: |
              {
                "message": "the data was entered properly"
              }
            
              
        
/{customerid}:
  uriParameters: 
    customerid:
      type: number
      example: 1
  get:
    description: get the customer details by customerid
    body:
      application/json:
        type: Customer
    
    
        
  put:
    description: Update a customer by customerId
    body:
      application/json:
        type: Customer
    responses:
      200:
        body:
          application/json:
            type: Result
            example: |
              {
                    "message":"Successfully updated the customer",
                    "code": 200
              }
        
        
          
  delete:
    description: Deleted a customer by customerId
    responses: 
      200:
        description: Sucessfully deleted the specific record
        body: 
          application/json:
            type: Result
            example: |
              {
                "message": "Successfully deleted a customer"
              }
           
        
 
      
    
